# nginx proxy address - http://172.17.0.1:6379


x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

name: redis
services:
  redis:
    image: redis:latest
    container_name: redis-app
    hostname: redis
    restart: always
    pull_policy: always
    logging: *default-logging
    command: >
      redis-server
      --save 60 1
      --loglevel warning
      --requirepass ${DB_ADMIN_PASS:-changeme_admin_password}
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: redis-app
    ports:
      - '6379:6379'
    volumes:
      - './volumes/data/db/redis:/data'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a "${DB_ADMIN_PASS:-changeme_admin_password}" ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    extra_hosts:
      - 'localhost:172.17.0.1'
      - 'host.docker.internal:host-gateway'
    networks:
      - redis

networks:
  redis:
    name: redis
    external: false
